[package]
name = "rust-scratch"
version = "0.1.0"
authors = ["Cem Catikkas <cem.catikkas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
